compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all  # Auto-detect all available GPUs
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: null  # Auto-detect based on available GPUs
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false